### ISSUE TITLE
GeneralLayout footer의 깃허브 링크 주소 수정

### ISSUE THREAD

**Issue by kennycha** [mooncastlestone/blog#1]
블로그 하단 카피라이트 내 깃허브 주소 클릭하면 없는 주소가 나와요!
깃허브 이름 변경하신 것 같은데, 요거 수정 필요할 것 같으네엽 👍 

[GeneralLayout > index.tsx](https://github.com/mooncastlestone/blog/blob/main/layouts/GeneralLayout/index.tsx) 26번째 라인

**Comment by mooncastlestone** [comment]
앗 그렇네여. 피드백 감사합니다 🙇🏻‍♂️🙇🏻‍♂️
